### ISSUE TITLE
The paper of this code

### ISSUE THREAD

**Issue by zyy-fc** [localmin/Multi-channel-NMF#3]
Could you tell me the name fo article you refer to ? 
The website  https://pdfs.semanticscholar.org/783f/44598d5d9df7d534d00943959d9b34dbc302.pdf bannot be accessed by me.

**Comment by localmin** [comment]
The name of  the article is "Multichannel Extensions of Non-Negative Matrix Factorization With Complex-Valued Data".  You can also see it the following link,  
[http://www.kecl.ntt.co.jp/people/kameoka.hirokazu/publications/Sawada2013IEEETrans05-published.pdf](http://www.kecl.ntt.co.jp/people/kameoka.hirokazu/publications/Sawada2013IEEETrans05-published.pdf)
I will modify the link of README.md soon.
